fix AppVeyor build: - move NODE_API_MODULE out of the NodeCld namespace (VS2015's non-conformant name lookup misresolves the macro's internal Napi::RegisterModule call as a member of NodeCld::Napi, causing error C2039) - add using NodeCld::Init declaration since NODE_API_MODULE token-pastes its argument and can't take a qualified name